"""Added age collumn in Employee table

Revision ID: 79b29b3eefcb
Revises: 4a0d3904f8df
Create Date: 2025-05-13 14:59:22.894816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b29b3eefcb'
down_revision: Union[str, None] = '4a0d3904f8df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('darbuotojai', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('darbuotojai', 'age')
    # ### end Alembic commands ###
